sudo: required
services:
    -   docker

before_install:
    - docker build -t pjeyabal15389/dockerReact -f Dockerfile.dev .

script:
    - docker run pjeyabal15389/dockerReact npm run test -- --coverage
